version: "3"
services:
  app:
    image: idrisfoughali/zoocontainer

    build:
      context: .
      dockerfile: Dockerfile
      labels:
      - "com.webapps.managment.zoo"
  #  volumes:
   #   - ./:/app
      
     ports:
      - "4000:4000"
      expose:
      - 4000

    environment:
      NODE_ENV: development

    environment:
      MYSQL_HOST: host.docker.internal
      MYSQL_USER: root
      MYSQL_PASSWORD: 
      MYSQL_DATABASE: nodejs
      MYSQL_PORT: 3306
     
     

#    links:
#      - mysql:mysql
#    depends_on:
#      - mysql
#    expose:
#      - 3000
