version: '3'
services:
  my-service:
    build:
      context: .
      dockerfile: dockerfile-alternate
    volumes:
      -  /usr/src/webapp/
    ports:
   #   - "5000:5000"
      - "10.0.75.1:5000:5000" 
    
   
   
  