version: '3'
services:
  my-service:
    image: my-image
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_HOST: host.docker.internal
      MYSQL_DATABASE: nodejs
      MYSQL_USER: root
      MYSQL_PASSWORD: 
      MYSQL_ROOT_PASSWORD: 
    ports:
      - "3307:3306"
    expose:
      - 3307
    expose:
      - 3306
  web:
    build:
      context: .
      dockerfile: /usr/src/app/Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      PORT: 4000
    links:
      - mysql:mysql
    depends_on:
      - mysql
    expose:
      - 4000
